version: '3.0'
services:
    core:
        container_name: core
        image: core
        hostname: core
        build:
            context: ./core
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - tms-datacenter
        links:
            - tms-datacenter
        networks:
            - app-network
        command: start
    edge:
        container_name: edge
        image: edge
        build:
            context: ./edge
            dockerfile: DockerFile
        ports:
            - 8080:8085
        depends_on:
            - core
        links:
            - core
        networks:
            - app-network
    datacenter:
        container_name: datacenter
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - datacenter:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tms
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - app-network

volumes:
    tms-datacenter: {}

networks:
  app-network:
    driver: bridge