version: '3.0'
services:
    core:
        container_name: core
        image: core
        hostname: core
        build:
            context: ./core
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - datacenter
            - kafka
        links:
            - datacenter
            - kafka
        networks:
            - app-network
        command: start
    edge:
        container_name: edge
        image: edge
        build:
            context: ./edge
            dockerfile: Dockerfile
        ports:
            - 8080:8085
        depends_on:
            - core
        links:
            - core
        networks:
            - app-network
    kafka:
        container_name: kafka
        image: kafka
        build:
            context: ./kafka
            dockerfile: DockerFile
        ports:
            - 9092:9092
            - 2181:2181
        environment:
            - ADVERTISED_PORT=9092
            - CONSUMER_THREADS=1
            - TOPICS=EmailTopic
            - ZK_CONNECT=kafka7zookeeper:2181/root/path
            - GROUP_ID=mymirror
        networks:
            - app-network
    datacenter:
        container_name: datacenter
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - datacenter:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tms
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - app-network

volumes:
    datacenter: {}

networks:
  app-network:
    driver: bridge